### ISSUE TITLE
Settings don't "stick" after clicking save.

### ISSUE THREAD

**Issue by rjc3rd** [Ahwxorg/LibreY#157] opened 2024-06-11 17:26 UTC
An example is like this.

Go to the settings page and change a few of things.
Theme - Light
Disable Frontends - Checked
Safe Search - Checked

Click save. You are taken back to start page and theme is correctly set to your new theme and I assume the frontends are disabled and safe search is on as you set them.

Don't make any searches yet though. You are still on the front page and all you've done is go to settings and make a few changes at this point.

Now go back to settings now for the second time, and sure enough the settings are still showing to be set the way you set them. Now don' make any changes here this time.

Click save, and again you are returned to the start page but the new settings are no longer set. You can tell initially that the theme is back to the default setting.

Plus if you go back to the settings a third time, you will see that all the setting you made are back to default settings.

Is this correct the expected and correct behavior?

**Comment by rjc3rd** [comment] 2024-06-11 18:05
I think it's related to the conflict between settings.php and config.php when index.php is reloaded.

I'm still trying to reverse engineer it. I'm a hack though. So it's tough for me to figure it out. I thought I'd ask here.

**Comment by rjc3rd** [comment] 2024-06-11 18:16
If you go first time and make changes but don't go back to settings, the setting do stick. I am able to search as many times as I like. Even if I leave the website and come back the settings are fine.

The problem only happens if you go back to the settings page, even if I don't actually make any changes. If I click save that second time, it reverts back to default.

Then I can go back and make the changes again just as if it was the first time again and it works again.

Not a deal breaker, but I'd like to solve it, if I can.

**Comment by Ahwxorg** [comment] 2024-06-12 10:56
This is not expected behavior, I tried to reproduce it and it's the same on my instance.

**Comment by Ahwxorg** [comment] 2024-06-12 10:56
> I think it's related to the conflict between settings.php and config.php when index.php is reloaded.
> 
> I'm still trying to reverse engineer it. I'm a hack though. So it's tough for me to figure it out. I thought I'd ask here.

I'll wait for your findings! (partially because I have no clue how to debug this myself lol)

**Comment by rjc3rd** [comment] 2024-06-12 18:55
I'm working on it today.

**Comment by Ahwxorg** [comment] 2024-06-12 20:02
Closing as this is completed in your PR.

**Closed by Ahwxorg** 2024-06-12 20:02 UTC
Labels: bug
